/* Lunara site behavior. Configuration is intentionally kept in one place. */
window.LUNARA_CONFIG = {
  brand: "Lunara Pearl Co.", currency: "USD", currencySymbol: "$",
  whatsappNumber: "15551234567", email: "hello@lunarapearl.com",
  instagram: "https://instagram.com/lunarapearlco",
  shippingText: "Complimentary shipping on orders over $150."
};

(function () {
  const products = window.LUNARA_PRODUCTS || [];
  const config = window.LUNARA_CONFIG;
  const page = document.body.dataset.page || "";
  const $ = (selector, scope = document) => scope.querySelector(selector);
  const $$ = (selector, scope = document) => [...scope.querySelectorAll(selector)];
  const money = value => `${config.currencySymbol}${Number(value).toLocaleString("en-US")}`;
  const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[char]));
  const categoryLabel = category => category.charAt(0).toUpperCase() + category.slice(1);
  const getProduct = id => products.find(product => product.id === id) || products[0];
  function getCart() { try { return JSON.parse(localStorage.getItem("lunara-cart") || "[]"); } catch { return []; } }
  function cartItems() { return getCart().map(item => ({...item, product: getProduct(item.id)})).filter(item => item.product); }
  function cartCount() { return getCart().reduce((sum, item) => sum + item.quantity, 0); }
  function cartTotal() { return cartItems().reduce((sum, item) => sum + item.product.price * item.quantity, 0); }
  function saveCart(cart) { localStorage.setItem("lunara-cart", JSON.stringify(cart)); updateCartUI(); }

  function renderChrome() {
    const header = $("#site-header"), footer = $("#site-footer"), overlays = $("#global-overlays");
    if (header) header.innerHTML = `<div class="announcement">${config.shippingText}</div><header class="site-header"><div class="site-header__inner container"><a class="brand" href="index.html" aria-label="${config.brand} home"><span class="brand-mark">L</span><span class="brand-name">${config.brand}</span></a><nav class="nav" id="main-nav"><a class="${page === "home" ? "is-active" : ""}" href="index.html">Home</a><a class="${page === "products" || page === "detail" ? "is-active" : ""}" href="products.html">Collections</a><a class="${page === "about" ? "is-active" : ""}" href="about.html">About</a><a class="${page === "contact" ? "is-active" : ""}" href="contact.html">Contact</a></nav><div class="header-actions"><button class="icon-button" data-open-search aria-label="Search products"><svg viewBox="0 0 24 24"><circle cx="10.8" cy="10.8" r="6.5"></circle><path d="m16 16 5 5"></path></svg></button><button class="icon-button" data-open-cart aria-label="Open shopping bag"><svg viewBox="0 0 24 24"><path d="M5 8h14l-1 13H6L5 8Z"></path><path d="M9 9V6a3 3 0 0 1 6 0v3"></path></svg><span class="cart-count" data-cart-count>0</span></button><button class="icon-button menu-toggle" data-toggle-menu aria-label="Open menu"><svg viewBox="0 0 24 24"><path d="M4 8h16M4 16h16"></path></svg></button></div></div></header>`;
    if (footer) footer.innerHTML = `<footer class="site-footer"><div class="container footer__top"><div class="footer__brand"><a class="brand" href="index.html"><span class="brand-mark">L</span><span class="brand-name">${config.brand}</span></a><p>A quieter kind of luxury, made luminous by nature.</p></div><div class="footer__col"><h3>Explore</h3><a href="products.html">All jewelry</a><a href="products.html?category=necklaces">Necklaces</a><a href="products.html?category=earrings">Earrings</a></div><div class="footer__col"><h3>About</h3><a href="about.html">Our story</a><a href="contact.html">Contact</a><a href="cart.html">Order request</a></div><div class="footer__col"><h3>Follow</h3><a href="${config.instagram}" target="_blank" rel="noreferrer">Instagram ↗</a><a href="mailto:${config.email}">${config.email}</a></div></div><div class="container footer__bottom"><span>© ${new Date().getFullYear()} ${config.brand}</span><span>Made for the moments that matter.</span></div></footer>`;
    if (overlays) overlays.innerHTML = `<div class="overlay" id="search-overlay"><section class="search-panel" aria-label="Product search"><div class="search-panel__top"><span class="eyebrow">Search the collection</span><input id="global-search" type="search" placeholder="Try “Akoya” or “necklace”" autocomplete="off"><button class="search-panel__close" data-close-overlay aria-label="Close search">×</button></div><div class="search-results" id="search-results"></div></section></div><div class="overlay" id="cart-overlay"><aside class="drawer" aria-label="Shopping bag"><div class="drawer__top"><h2>Your bag</h2><button class="drawer__close" data-close-overlay aria-label="Close shopping bag">×</button></div><div class="drawer__items" id="drawer-items"></div><div class="drawer__footer" id="drawer-footer"></div></aside></div>`;
  }
  function productCard(product) { return `<article class="product-card"><a class="product-card__image" href="product-detail.html?id=${product.id}"><img loading="lazy" src="${product.image}" alt="${escapeHtml(product.name)}" width="500" height="625">${product.oldPrice ? '<span class="sale-tag">Limited edit</span>' : ''}</a><div class="product-card__meta"><div><h3><a href="product-detail.html?id=${product.id}">${escapeHtml(product.name)}</a></h3><p>${escapeHtml(product.pearlType)} · ${categoryLabel(product.category)}</p></div><div class="price">${product.oldPrice ? `<s>${money(product.oldPrice)}</s>` : ""}${money(product.price)}</div></div></article>`; }
  function renderHome() { const collection = $("#collection-grid"), featured = $("#featured-products"); if (collection) collection.innerHTML = ["necklaces","earrings","bracelets","rings","sets"].map(category => `<a class="collection-card" href="products.html?category=${category}"><span class="collection-card__art" style="background-image:url('images/collection-${category}.svg')"></span><span class="collection-card__label">Pearl ${categoryLabel(category)}</span></a>`).join(""); if (featured) featured.innerHTML = products.slice(0, 8).map(productCard).join(""); }
  function renderCatalog() {
    const grid = $("#catalog-grid"); if (!grid) return;
    let filter = new URLSearchParams(location.search).get("category") || "all", sort = "featured"; const pills = $$(".filter-pill");
    const paint = () => { let list = products.filter(product => filter === "all" || product.category === filter); if (sort === "low") list.sort((a, b) => a.price - b.price); if (sort === "high") list.sort((a, b) => b.price - a.price); grid.innerHTML = list.map(productCard).join(""); $("#catalog-count").textContent = `${String(list.length).padStart(2, "0")} pieces`; $("#catalog-empty").hidden = list.length > 0; pills.forEach(pill => pill.classList.toggle("is-active", pill.dataset.filter === filter)); };
    pills.forEach(pill => pill.addEventListener("click", () => { filter = pill.dataset.filter; paint(); })); $("#sort-products")?.addEventListener("change", event => { sort = event.target.value; paint(); }); $("[data-clear-filters]")?.addEventListener("click", () => { filter = "all"; sort = "featured"; $("#sort-products").value = "featured"; paint(); }); paint();
  }
  function renderDetail() {
    const id = new URLSearchParams(location.search).get("id"), product = getProduct(id), main = $("#detail-main-image"), thumbs = $("#detail-thumbnails"), info = $("#detail-info"); if (!main || !info) return;
    document.title = `${product.name} | ${config.brand}`; $("#breadcrumb-name").textContent = product.name; main.innerHTML = `<img src="${product.image}" alt="${escapeHtml(product.name)}" width="800" height="880">`; thumbs.innerHTML = [product.image, product.image, product.image].map((image, index) => `<button class="thumbnail ${index === 0 ? "is-active" : ""}" data-thumb="${image}" aria-label="View image ${index + 1}"><img src="${image}" alt=""></button>`).join("");
    $$(`[data-thumb]`, thumbs).forEach(button => button.addEventListener("click", () => { $("img", main).src = button.dataset.thumb; $$(`[data-thumb]`, thumbs).forEach(item => item.classList.remove("is-active")); button.classList.add("is-active"); }));
    info.innerHTML = `<p class="eyebrow">${categoryLabel(product.category)} · ${product.pearlType}</p><h1>${escapeHtml(product.name)}</h1><p class="detail__price">${money(product.price)}${product.oldPrice ? ` <s class="muted">${money(product.oldPrice)}</s>` : ""}</p><p class="detail__description">${escapeHtml(product.description)}</p><dl class="detail-specs"><div><dt>Pearl type</dt><dd>${escapeHtml(product.pearlType)}</dd></div><div><dt>Pearl size</dt><dd>${escapeHtml(product.size)}</dd></div><div><dt>Material</dt><dd>${escapeHtml(product.material)}</dd></div><div><dt>Dimensions</dt><dd>${escapeHtml(product.dimensions)}</dd></div><div><dt>Product code</dt><dd>${escapeHtml(product.code)}</dd></div><div><dt>Availability</dt><dd>Ready to ship</dd></div></dl><div class="quantity-row"><div class="quantity-control"><button type="button" data-qty-minus aria-label="Decrease quantity">−</button><input id="detail-quantity" value="1" min="1" max="10" type="number" aria-label="Quantity"><button type="button" data-qty-plus aria-label="Increase quantity">+</button></div><button class="button button--dark add-button" data-add-product="${product.id}">Add to bag <span aria-hidden="true">↗</span></button></div><p class="availability">● In stock · Complimentary gift packaging</p>`;
    $("[data-qty-minus]")?.addEventListener("click", () => changeInput(-1)); $("[data-qty-plus]")?.addEventListener("click", () => changeInput(1)); $("[data-add-product]")?.addEventListener("click", () => addToCart(product.id, Number($("#detail-quantity").value) || 1)); const related = $("#related-products"); if (related) related.innerHTML = products.filter(item => item.id !== product.id && item.category === product.category).slice(0, 4).concat(products.filter(item => item.id !== product.id && item.category !== product.category).slice(0, 4)).slice(0, 4).map(productCard).join("");
  }
  function changeInput(amount) { const input = $("#detail-quantity"); if (input) input.value = Math.min(10, Math.max(1, (Number(input.value) || 1) + amount)); }
  function addToCart(id, quantity = 1) { const cart = getCart(), existing = cart.find(item => item.id === id); if (existing) existing.quantity = Math.min(10, existing.quantity + quantity); else cart.push({id, quantity: Math.min(10, quantity)}); saveCart(cart); openOverlay("#cart-overlay"); }
  function removeFromCart(id) { saveCart(getCart().filter(item => item.id !== id)); if (page === "cart") renderCartPage(); }
  function setQuantity(id, quantity) { const cart = getCart(), item = cart.find(entry => entry.id === id); if (item) item.quantity = Math.min(10, Math.max(1, quantity)); saveCart(cart); if (page === "cart") renderCartPage(); }
  function renderDrawer() {
    const items = $("#drawer-items"), footer = $("#drawer-footer"); if (!items || !footer) return; const current = cartItems();
    items.innerHTML = current.length ? current.map(item => `<div class="drawer-item"><img src="${item.product.image}" alt="${escapeHtml(item.product.name)}"><div><h3>${escapeHtml(item.product.name)}</h3><p>${item.quantity} × ${money(item.product.price)}</p></div><button class="drawer-item__remove" data-remove="${item.product.id}" aria-label="Remove ${escapeHtml(item.product.name)}">×</button></div>`).join("") : `<div class="empty-cart"><span class="empty-state__mark">◌</span><h3>Your bag is quiet.</h3><p class="cart-empty-note">Add a piece that feels like you.</p></div>`;
    footer.innerHTML = current.length ? `<div class="drawer-subtotal"><span>Subtotal</span><span>${money(cartTotal())}</span></div><a class="button button--dark" href="cart.html">Review your bag <span aria-hidden="true">↗</span></a><a class="text-link" href="products.html">Continue shopping</a>` : "";
  }
  function updateCartUI() { $$("[data-cart-count]").forEach(element => { element.textContent = cartCount(); element.hidden = cartCount() === 0; }); renderDrawer(); if (page === "cart") renderCartPage(); }
  function renderCartPage() {
    const holder = $("#cart-page-items"), summary = $("#cart-summary"); if (!holder || !summary) return; const current = cartItems();
    holder.innerHTML = current.length ? current.map(item => `<div class="cart-item"><div class="cart-item__image"><img src="${item.product.image}" alt="${escapeHtml(item.product.name)}"></div><div class="cart-item__info"><h3>${escapeHtml(item.product.name)}</h3><p>${escapeHtml(item.product.pearlType)}</p><button class="cart-item__remove" data-remove-page="${item.product.id}">Remove</button></div><div class="cart-item__price"><strong>${money(item.product.price * item.quantity)}</strong><div class="quantity-control"><button data-page-minus="${item.product.id}" aria-label="Decrease quantity">−</button><input value="${item.quantity}" data-page-input="${item.product.id}" min="1" max="10" type="number" aria-label="Quantity"><button data-page-plus="${item.product.id}" aria-label="Increase quantity">+</button></div></div></div>`).join("") : `<div class="empty-cart"><span class="empty-state__mark">◌</span><h3>Your bag is quiet.</h3><p class="cart-empty-note">There’s always room for one more luminous thing.</p><a class="button button--dark" href="products.html">Explore collection <span aria-hidden="true">↗</span></a></div>`;
    summary.innerHTML = `<div class="summary"><div class="summary__row"><span>Subtotal</span><span>${money(cartTotal())}</span></div><div class="summary__row"><span>Shipping</span><span>${cartTotal() >= 150 || cartTotal() === 0 ? "Complimentary" : "Calculated with confirmation"}</span></div><div class="summary__row summary__row--total"><span>Total</span><span>${money(cartTotal())}</span></div></div>`;
    $$(`[data-remove-page]`, holder).forEach(button => button.addEventListener("click", () => removeFromCart(button.dataset.removePage))); $$(`[data-page-minus]`, holder).forEach(button => button.addEventListener("click", () => setQuantity(button.dataset.pageMinus, Number($(`[data-page-input="${button.dataset.pageMinus}"]`, holder).value) - 1))); $$(`[data-page-plus]`, holder).forEach(button => button.addEventListener("click", () => setQuantity(button.dataset.pagePlus, Number($(`[data-page-input="${button.dataset.pagePlus}"]`, holder).value) + 1))); $$(`[data-page-input]`, holder).forEach(input => input.addEventListener("change", () => setQuantity(input.dataset.pageInput, Number(input.value))));
  }
  function renderSearch(query) {
    const results = $("#search-results"); if (!results) return; const normalized = query.trim().toLowerCase(); const found = normalized ? products.filter(product => [product.name, product.category, product.pearlType].join(" ").toLowerCase().includes(normalized)).slice(0, 8) : products.slice(0, 4);
    results.innerHTML = found.length ? found.map(product => `<a class="search-result" href="product-detail.html?id=${product.id}"><img src="${product.image}" alt=""><span><h3>${escapeHtml(product.name)}</h3><p>${escapeHtml(product.pearlType)} · ${money(product.price)}</p></span></a>`).join("") : `<p class="muted">No pieces match “${escapeHtml(query)}”.</p>`;
  }
  function openOverlay(id) { const overlay = $(id); if (!overlay) return; overlay.classList.add("is-open"); document.body.classList.add("no-scroll"); if (id === "#search-overlay") { $("#global-search")?.focus(); renderSearch(""); } else renderDrawer(); }
  function closeOverlays() { $$(".overlay.is-open").forEach(element => element.classList.remove("is-open")); document.body.classList.remove("no-scroll"); }
  function handleOrder(event) {
    event.preventDefault(); if (!cartItems().length) { $("#order-message").textContent = "Your bag is empty—add a piece before placing an order request."; return; }
    const data = new FormData(event.target), lines = cartItems().map(item => `${item.quantity} × ${item.product.name} — ${money(item.product.price * item.quantity)}`).join("%0A"); const message = `Hello ${config.brand},%0A%0AI'd like to place an order request:%0A${lines}%0A%0ATotal: ${money(cartTotal())}%0A%0AName: ${encodeURIComponent(data.get("name"))}%0APhone: ${encodeURIComponent(data.get("phone"))}%0AEmail: ${encodeURIComponent(data.get("email"))}%0AAddress: ${encodeURIComponent(data.get("address"))}%0ANote: ${encodeURIComponent(data.get("note") || "—")}`;
    window.open(`https://wa.me/${config.whatsappNumber}?text=${message}`, "_blank", "noopener"); $("#order-message").textContent = "Your order request is ready to send in WhatsApp.";
  }
  function bindGlobal() {
    document.addEventListener("click", event => { const openSearch = event.target.closest("[data-open-search]"), openCart = event.target.closest("[data-open-cart]"), close = event.target.closest("[data-close-overlay]"), remove = event.target.closest("[data-remove]"); if (openSearch || openCart) { event.preventDefault(); openOverlay(openSearch ? "#search-overlay" : "#cart-overlay"); } if (close || event.target.classList.contains("overlay")) closeOverlays(); if (remove) removeFromCart(remove.dataset.remove); });
    $("#global-search")?.addEventListener("input", event => renderSearch(event.target.value)); $("[data-toggle-menu]")?.addEventListener("click", () => $("#main-nav")?.classList.toggle("is-open")); $("#clear-cart")?.addEventListener("click", () => { saveCart([]); renderCartPage(); }); $("#contact-form")?.addEventListener("submit", event => { event.preventDefault(); $("#contact-message").textContent = "Thank you—your note is on its way. We’ll be in touch shortly."; event.target.reset(); }); $("#order-form")?.addEventListener("submit", handleOrder);
  }
  renderChrome(); bindGlobal(); updateCartUI(); if (page === "home") renderHome(); if (page === "products") renderCatalog(); if (page === "detail") renderDetail(); if (page === "cart") renderCartPage();
})();
