/* Tâm Ý Jewelry — toàn bộ cấu hình và hành vi giao diện nằm trong tệp này. */
window.LUNARA_CONFIG = {
  brand: "Tâm Ý Jewelry",
  currency: "USD",
  currencySymbol: "$",
  whatsappNumber: "84339098834",
  email: "hello@lunarapearl.com",
  facebook: "https://www.facebook.com/profile.php?id=100072026703972",
  shippingText: "Miễn phí vận chuyển cho đơn từ $150."
};

(function () {
  const products = window.LUNARA_PRODUCTS || [];
  const config = window.LUNARA_CONFIG;
  const page = document.body.dataset.page || "";
  const $ = (selector, scope = document) => scope.querySelector(selector);
  const $$ = (selector, scope = document) => [...scope.querySelectorAll(selector)];
  const money = value => `${config.currencySymbol}${Number(value).toLocaleString("en-US")}`;
  const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[char]));
  const categoryLabels = {all:"Tất cả", necklaces:"Dây chuyền", earrings:"Bông tai", bracelets:"Vòng tay", rings:"Nhẫn", sets:"Set trang sức"};
  const categoryLabel = category => categoryLabels[category] || category;
  const getProduct = id => products.find(product => product.id === id) || products[0];
  function getCart() { try { return JSON.parse(localStorage.getItem("lunara-cart") || "[]"); } catch { return []; } }
  function cartItems() { return getCart().map(item => ({...item, product: getProduct(item.id)})).filter(item => item.product); }
  function cartCount() { return getCart().reduce((sum, item) => sum + item.quantity, 0); }
  function cartTotal() { return cartItems().reduce((sum, item) => sum + item.product.price * item.quantity, 0); }
  function saveCart(cart) { localStorage.setItem("lunara-cart", JSON.stringify(cart)); updateCartUI(); }

  function renderChrome() {
    const header = $("#site-header"), footer = $("#site-footer"), overlays = $("#global-overlays");
    if (header) header.innerHTML = `<div class="announcement">${config.shippingText}</div><header class="site-header"><div class="site-header__inner container"><a class="brand" href="index.html" aria-label="Trang chủ ${config.brand}"><span class="brand-mark">T</span><span class="brand-name">${config.brand}</span></a><nav class="nav" id="main-nav"><a class="${page === "home" ? "is-active" : ""}" href="index.html">Trang chủ</a><a class="${page === "products" || page === "detail" ? "is-active" : ""}" href="products.html">Bộ sưu tập</a><a class="${page === "about" ? "is-active" : ""}" href="about.html">Về Tâm Ý</a><a class="${page === "contact" ? "is-active" : ""}" href="contact.html">Liên hệ</a></nav><div class="header-actions"><button class="icon-button" data-open-search aria-label="Tìm kiếm sản phẩm"><svg viewBox="0 0 24 24"><circle cx="10.8" cy="10.8" r="6.5"></circle><path d="m16 16 5 5"></path></svg></button><button class="icon-button" data-open-cart aria-label="Mở giỏ hàng"><svg viewBox="0 0 24 24"><path d="M5 8h14l-1 13H6L5 8Z"></path><path d="M9 9V6a3 3 0 0 1 6 0v3"></path></svg><span class="cart-count" data-cart-count>0</span></button><button class="icon-button menu-toggle" data-toggle-menu aria-label="Mở menu"><svg viewBox="0 0 24 24"><path d="M4 8h16M4 16h16"></path></svg></button></div></div></header>`;
    if (footer) footer.innerHTML = `<footer class="site-footer"><div class="container footer__top"><div class="footer__brand"><a class="brand" href="index.html"><span class="brand-mark">T</span><span class="brand-name">${config.brand}</span></a><p>Trang sức ngọc trai tinh tế, được tạo nên cho những khoảnh khắc đáng nhớ.</p></div><div class="footer__col"><h3>Khám phá</h3><a href="products.html">Tất cả sản phẩm</a><a href="products.html?category=necklaces">Dây chuyền</a><a href="products.html?category=earrings">Bông tai</a></div><div class="footer__col"><h3>Thông tin</h3><a href="about.html">Câu chuyện thương hiệu</a><a href="contact.html">Liên hệ</a><a href="cart.html">Đặt hàng</a></div><div class="footer__col"><h3>Kết nối</h3><a href="${config.facebook}" target="_blank" rel="noreferrer">Facebook ↗</a><a href="tel:+84339098834">+84 33 909 8834</a><a href="mailto:${config.email}">${config.email}</a></div></div><div class="container footer__bottom"><span>© ${new Date().getFullYear()} ${config.brand}</span><span>Đẹp cho những khoảnh khắc đáng nhớ.</span></div></footer>`;
    if (overlays) overlays.innerHTML = `<div class="overlay" id="search-overlay"><section class="search-panel" aria-label="Tìm kiếm sản phẩm"><div class="search-panel__top"><span class="eyebrow">Tìm trong bộ sưu tập</span><input id="global-search" type="search" placeholder="Thử “Akoya” hoặc “dây chuyền”" autocomplete="off"><button class="search-panel__close" data-close-overlay aria-label="Đóng tìm kiếm">×</button></div><div class="search-results" id="search-results"></div></section></div><div class="overlay" id="cart-overlay"><aside class="drawer" aria-label="Giỏ hàng"><div class="drawer__top"><h2>Giỏ hàng</h2><button class="drawer__close" data-close-overlay aria-label="Đóng giỏ hàng">×</button></div><div class="drawer__items" id="drawer-items"></div><div class="drawer__footer" id="drawer-footer"></div></aside></div>`;
  }
  function productCard(product) { return `<article class="product-card"><a class="product-card__image" href="product-detail.html?id=${product.id}"><img loading="lazy" src="${product.image}" alt="${escapeHtml(product.name)}" width="500" height="625">${product.oldPrice ? '<span class="sale-tag">Ưu đãi đặc biệt</span>' : ''}</a><div class="product-card__meta"><div><h3><a href="product-detail.html?id=${product.id}">${escapeHtml(product.name)}</a></h3><p>${escapeHtml(product.pearlType)} · ${categoryLabel(product.category)}</p></div><div class="price">${product.oldPrice ? `<s>${money(product.oldPrice)}</s>` : ""}${money(product.price)}</div></div></article>`; }
  function renderHome() { const collection = $("#collection-grid"), featured = $("#featured-products"); if (collection) collection.innerHTML = ["necklaces","earrings","bracelets","rings","sets"].map(category => `<a class="collection-card" href="products.html?category=${category}"><span class="collection-card__art" style="background-image:url('images/collection-${category}.svg')"></span><span class="collection-card__label">${category === "sets" ? "Set ngọc trai" : `${categoryLabel(category)} ngọc trai`}</span></a>`).join(""); if (featured) featured.innerHTML = products.slice(0, 8).map(productCard).join(""); }
  function renderCatalog() { const grid = $("#catalog-grid"); if (!grid) return; let filter = new URLSearchParams(location.search).get("category") || "all", sort = "featured"; const pills = $$(".filter-pill"); const paint = () => { let list = products.filter(product => filter === "all" || product.category === filter); if (sort === "low") list.sort((a, b) => a.price - b.price); if (sort === "high") list.sort((a, b) => b.price - a.price); grid.innerHTML = list.map(productCard).join(""); $("#catalog-count").textContent = `${String(list.length).padStart(2, "0")} sản phẩm`; $("#catalog-empty").hidden = list.length > 0; pills.forEach(pill => pill.classList.toggle("is-active", pill.dataset.filter === filter)); }; pills.forEach(pill => pill.addEventListener("click", () => { filter = pill.dataset.filter; paint(); })); $("#sort-products")?.addEventListener("change", event => { sort = event.target.value; paint(); }); $("[data-clear-filters]")?.addEventListener("click", () => { filter = "all"; sort = "featured"; $("#sort-products").value = "featured"; paint(); }); paint(); }
  function renderDetail() { const id = new URLSearchParams(location.search).get("id"), product = getProduct(id), main = $("#detail-main-image"), thumbs = $("#detail-thumbnails"), info = $("#detail-info"); if (!main || !info || !product) return; document.title = `${product.name} | ${config.brand}`; $("#breadcrumb-name").textContent = product.name; main.innerHTML = `<img src="${product.image}" alt="${escapeHtml(product.name)}" width="800" height="880">`; thumbs.innerHTML = [product.image, product.image, product.image].map((image, index) => `<button class="thumbnail ${index === 0 ? "is-active" : ""}" data-thumb="${image}" aria-label="Xem ảnh ${index + 1}"><img src="${image}" alt=""></button>`).join(""); $$(`[data-thumb]`, thumbs).forEach(button => button.addEventListener("click", () => { $("img", main).src = button.dataset.thumb; $$(`[data-thumb]`, thumbs).forEach(item => item.classList.remove("is-active")); button.classList.add("is-active"); })); info.innerHTML = `<p class="eyebrow">${categoryLabel(product.category)} · ${product.pearlType}</p><h1>${escapeHtml(product.name)}</h1><p class="detail__price">${money(product.price)}${product.oldPrice ? ` <s class="muted">${money(product.oldPrice)}</s>` : ""}</p><p class="detail__description">${escapeHtml(product.description)}</p><dl class="detail-specs"><div><dt>Loại ngọc</dt><dd>${escapeHtml(product.pearlType)}</dd></div><div><dt>Kích thước ngọc</dt><dd>${escapeHtml(product.size)}</dd></div><div><dt>Chất liệu</dt><dd>${escapeHtml(product.material)}</dd></div><div><dt>Kích thước</dt><dd>${escapeHtml(product.dimensions)}</dd></div><div><dt>Mã sản phẩm</dt><dd>${escapeHtml(product.code)}</dd></div><div><dt>Tình trạng</dt><dd>Còn hàng</dd></div></dl><div class="quantity-row"><div class="quantity-control"><button type="button" data-qty-minus aria-label="Giảm số lượng">−</button><input id="detail-quantity" value="1" min="1" max="10" type="number" aria-label="Số lượng"><button type="button" data-qty-plus aria-label="Tăng số lượng">+</button></div><button class="button button--dark add-button" data-add-product="${product.id}">Thêm vào giỏ <span aria-hidden="true">↗</span></button></div><p class="availability">● Còn hàng · Tặng kèm hộp quà</p>`; $("[data-qty-minus]")?.addEventListener("click", () => changeInput(-1)); $("[data-qty-plus]")?.addEventListener("click", () => changeInput(1)); $("[data-add-product]")?.addEventListener("click", () => addToCart(product.id, Number($("#detail-quantity").value) || 1)); const related = $("#related-products"); if (related) related.innerHTML = products.filter(item => item.id !== product.id && item.category === product.category).slice(0, 4).concat(products.filter(item => item.id !== product.id && item.category !== product.category).slice(0, 4)).slice(0, 4).map(productCard).join(""); }
  function changeInput(amount) { const input = $("#detail-quantity"); if (input) input.value = Math.min(10, Math.max(1, (Number(input.value) || 1) + amount)); }
  function addToCart(id, quantity = 1) { const cart = getCart(), existing = cart.find(item => item.id === id); if (existing) existing.quantity = Math.min(10, existing.quantity + quantity); else cart.push({id, quantity: Math.min(10, quantity)}); saveCart(cart); openOverlay("#cart-overlay"); }
  function removeFromCart(id) { saveCart(getCart().filter(item => item.id !== id)); if (page === "cart") renderCartPage(); }
  function setQuantity(id, quantity) { const cart = getCart(), item = cart.find(entry => entry.id === id); if (item) item.quantity = Math.min(10, Math.max(1, quantity)); saveCart(cart); if (page === "cart") renderCartPage(); }
  function renderDrawer() { const items = $("#drawer-items"), footer = $("#drawer-footer"); if (!items || !footer) return; const current = cartItems(); items.innerHTML = current.length ? current.map(item => `<div class="drawer-item"><img src="${item.product.image}" alt="${escapeHtml(item.product.name)}"><div><h3>${escapeHtml(item.product.name)}</h3><p>${item.quantity} × ${money(item.product.price)}</p></div><button class="drawer-item__remove" data-remove="${item.product.id}" aria-label="Xóa ${escapeHtml(item.product.name)}">×</button></div>`).join("") : `<div class="empty-cart"><span class="empty-state__mark">◌</span><h3>Giỏ hàng đang trống.</h3><p class="cart-empty-note">Hãy thêm một món trang sức dành riêng cho bạn.</p></div>`; footer.innerHTML = current.length ? `<div class="drawer-subtotal"><span>Tạm tính</span><span>${money(cartTotal())}</span></div><a class="button button--dark" href="cart.html">Xem giỏ hàng <span aria-hidden="true">↗</span></a><a class="text-link" href="products.html">Tiếp tục mua sắm</a>` : ""; }
  function updateCartUI() { $$("[data-cart-count]").forEach(element => { element.textContent = cartCount(); element.hidden = cartCount() === 0; }); renderDrawer(); if (page === "cart") renderCartPage(); }
  function renderCartPage() { const holder = $("#cart-page-items"), summary = $("#cart-summary"); if (!holder || !summary) return; const current = cartItems(); holder.innerHTML = current.length ? current.map(item => `<div class="cart-item"><div class="cart-item__image"><img src="${item.product.image}" alt="${escapeHtml(item.product.name)}"></div><div class="cart-item__info"><h3>${escapeHtml(item.product.name)}</h3><p>${escapeHtml(item.product.pearlType)}</p><button class="cart-item__remove" data-remove-page="${item.product.id}">Xóa</button></div><div class="cart-item__price"><strong>${money(item.product.price * item.quantity)}</strong><div class="quantity-control"><button data-page-minus="${item.product.id}" aria-label="Giảm số lượng">−</button><input value="${item.quantity}" data-page-input="${item.product.id}" min="1" max="10" type="number" aria-label="Số lượng"><button data-page-plus="${item.product.id}" aria-label="Tăng số lượng">+</button></div></div></div>`).join("") : `<div class="empty-cart"><span class="empty-state__mark">◌</span><h3>Giỏ hàng đang trống.</h3><p class="cart-empty-note">Vẫn còn chỗ cho một món trang sức rạng ngời.</p><a class="button button--dark" href="products.html">Khám phá bộ sưu tập <span aria-hidden="true">↗</span></a></div>`; summary.innerHTML = `<div class="summary"><div class="summary__row"><span>Tạm tính</span><span>${money(cartTotal())}</span></div><div class="summary__row"><span>Vận chuyển</span><span>${cartTotal() >= 150 || cartTotal() === 0 ? "Miễn phí" : "Xác nhận sau"}</span></div><div class="summary__row summary__row--total"><span>Tổng cộng</span><span>${money(cartTotal())}</span></div></div>`; $$(`[data-remove-page]`, holder).forEach(button => button.addEventListener("click", () => removeFromCart(button.dataset.removePage))); $$(`[data-page-minus]`, holder).forEach(button => button.addEventListener("click", () => setQuantity(button.dataset.pageMinus, Number($(`[data-page-input="${button.dataset.pageMinus}"]`, holder).value) - 1))); $$(`[data-page-plus]`, holder).forEach(button => button.addEventListener("click", () => setQuantity(button.dataset.pagePlus, Number($(`[data-page-input="${button.dataset.pagePlus}"]`, holder).value) + 1))); $$(`[data-page-input]`, holder).forEach(input => input.addEventListener("change", () => setQuantity(input.dataset.pageInput, Number(input.value)))); }
  function renderSearch(query) { const results = $("#search-results"); if (!results) return; const normalized = query.trim().toLowerCase(); const found = normalized ? products.filter(product => [product.name, product.category, product.pearlType].join(" ").toLowerCase().includes(normalized)).slice(0, 8) : products.slice(0, 4); results.innerHTML = found.length ? found.map(product => `<a class="search-result" href="product-detail.html?id=${product.id}"><img src="${product.image}" alt=""><span><h3>${escapeHtml(product.name)}</h3><p>${escapeHtml(product.pearlType)} · ${money(product.price)}</p></span></a>`).join("") : `<p class="muted">Không tìm thấy sản phẩm phù hợp với “${escapeHtml(query)}”.</p>`; }
  function openOverlay(id) { const overlay = $(id); if (!overlay) return; overlay.classList.add("is-open"); document.body.classList.add("no-scroll"); if (id === "#search-overlay") { $("#global-search")?.focus(); renderSearch(""); } else renderDrawer(); }
  function closeOverlays() { $$(".overlay.is-open").forEach(element => element.classList.remove("is-open")); document.body.classList.remove("no-scroll"); }
  function handleOrder(event) { event.preventDefault(); if (!cartItems().length) { $("#order-message").textContent = "Giỏ hàng đang trống. Hãy thêm sản phẩm trước khi gửi yêu cầu."; return; } const data = new FormData(event.target), lines = cartItems().map(item => `${item.quantity} × ${item.product.name} — ${money(item.product.price * item.quantity)}`).join("\n"); const message = [`Xin chào ${config.brand},`, "", "Tôi muốn gửi yêu cầu đặt hàng:", lines, "", `Tổng cộng: ${money(cartTotal())}`, "", `Họ tên: ${data.get("name")}`, `Điện thoại: ${data.get("phone")}`, `Email: ${data.get("email")}`, `Địa chỉ: ${data.get("address")}`, `Ghi chú: ${data.get("note") || "—"}`].join("\n"); window.open(`https://wa.me/${config.whatsappNumber}?text=${encodeURIComponent(message)}`, "_blank", "noopener"); $("#order-message").textContent = "Yêu cầu đặt hàng đã sẵn sàng để gửi qua WhatsApp."; }
  function bindGlobal() { document.addEventListener("click", event => { const openSearch = event.target.closest("[data-open-search]"), openCart = event.target.closest("[data-open-cart]"), close = event.target.closest("[data-close-overlay]"), remove = event.target.closest("[data-remove]"); if (openSearch || openCart) { event.preventDefault(); openOverlay(openSearch ? "#search-overlay" : "#cart-overlay"); } if (close || event.target.classList.contains("overlay")) closeOverlays(); if (remove) removeFromCart(remove.dataset.remove); }); $("#global-search")?.addEventListener("input", event => renderSearch(event.target.value)); $("[data-toggle-menu]")?.addEventListener("click", () => $("#main-nav")?.classList.toggle("is-open")); $("#clear-cart")?.addEventListener("click", () => { saveCart([]); renderCartPage(); }); $("#contact-form")?.addEventListener("submit", event => { event.preventDefault(); $("#contact-message").textContent = "Cảm ơn bạn. Tin nhắn đã được gửi, chúng tôi sẽ liên hệ sớm."; event.target.reset(); }); $("#order-form")?.addEventListener("submit", handleOrder); }
  renderChrome(); bindGlobal(); updateCartUI(); if (page === "home") renderHome(); if (page === "products") renderCatalog(); if (page === "detail") renderDetail(); if (page === "cart") renderCartPage();
})();

