/* Central product catalog. Replace image paths, prices, and copy here. */
window.LUNARA_PRODUCTS = [
  {id:"luna-necklace",name:"Luna Pearl Necklace",category:"necklaces",pearlType:"Freshwater Pearl",price:189,material:"14k gold vermeil",size:"7–7.5 mm",dimensions:"16 in + 2 in extender",code:"LUN-N01",image:"images/luna-necklace.svg",description:"A luminous strand with a softly irregular rhythm—finished with a sculptural toggle clasp designed to sit beautifully at the front or back."},
  {id:"royal-earrings",name:"Royal Pearl Earrings",category:"earrings",pearlType:"South Sea Pearl",price:329,material:"14k gold vermeil",size:"10 mm",dimensions:"0.8 in drop",code:"LUN-E02",image:"images/royal-earrings.svg",description:"The classic drop, thoughtfully scaled. Creamy South Sea pearls bring a warm, exceptional glow to every occasion."},
  {id:"etoile-bracelet",name:"Étoile Pearl Bracelet",category:"bracelets",pearlType:"Freshwater Pearl",price:219,material:"Sterling silver",size:"6.5–7 mm",dimensions:"6.5 in + 1 in extender",code:"LUN-B03",image:"images/etoile-bracelet.svg",description:"A delicate constellation of pearls and tiny polished stars, made to be worn alone or layered with your everyday favorites."},
  {id:"aurora-ring",name:"Aurora Pearl Ring",category:"rings",pearlType:"Akoya Pearl",price:289,material:"18k gold vermeil",size:"8 mm",dimensions:"Adjustable band",code:"LUN-R04",image:"images/aurora-ring.svg",description:"A single Akoya pearl held in a light-catching, fluid setting. An everyday talisman with a quietly luminous presence."},
  {id:"celeste-set",name:"Celeste Pearl Set",category:"sets",pearlType:"Freshwater Pearl",price:395,oldPrice:438,material:"14k gold vermeil",size:"7 mm",dimensions:"Necklace 16 in · studs 0.4 in",code:"LUN-S05",image:"images/celeste-set.svg",description:"A considered pairing of our Celeste studs and a fine pearl chain—gift-ready and designed to make getting dressed feel easy."},
  {id:"maris-hoops",name:"Maris Pearl Hoops",category:"earrings",pearlType:"Freshwater Pearl",price:159,material:"Gold-filled",size:"6 mm",dimensions:"0.7 in diameter",code:"LUN-E06",image:"images/maris-hoops.svg",description:"Slim, polished hoops punctuated by petite pearls. The pair you reach for when you want just a touch of light."},
  {id:"solace-necklace",name:"Solace Pendant",category:"necklaces",pearlType:"Baroque Pearl",price:249,material:"Sterling silver",size:"9–10 mm",dimensions:"18 in chain",code:"LUN-N07",image:"images/solace-necklace.svg",description:"A one-of-a-kind baroque pearl suspended from a clean silver line. Organic, modern, and entirely individual."},
  {id:"nacre-stack",name:"Nacre Ring Stack",category:"rings",pearlType:"Akoya Pearl",price:310,material:"14k solid gold",size:"6 mm",dimensions:"Sizes 5–9",code:"LUN-R08",image:"images/nacre-stack.svg",description:"Two fine bands, one petite Akoya pearl. A sculptural stack with just enough asymmetry to feel personal."}
];

