/* Danh mục sản phẩm tập trung. Chỉnh sửa sản phẩm, giá và ảnh tại đây. */
window.LUNARA_PRODUCTS = [
  {id:"luna-necklace",name:"Vòng cổ ngọc trai Luna",category:"necklaces",pearlType:"Ngọc trai nước ngọt",price:189,material:"Vàng vermeil 14K",size:"7–7,5 mm",dimensions:"Dài 16 inch + dây nối 2 inch",code:"TY-N01",image:"images/luna-necklace.svg",description:"Chuỗi ngọc trai rạng ngời với nhịp điệu tự nhiên nhẹ nhàng, hoàn thiện bằng khóa gài điêu khắc có thể đeo ở phía trước hoặc sau."},
  {id:"royal-earrings",name:"Bông tai ngọc trai Royal",category:"earrings",pearlType:"Ngọc trai South Sea",price:329,material:"Vàng vermeil 14K",size:"10 mm",dimensions:"Dài rủ 0,8 inch",code:"TY-E02",image:"images/royal-earrings.svg",description:"Thiết kế bông tai rủ kinh điển với tỷ lệ vừa vặn. Ngọc trai South Sea màu kem mang đến ánh sáng ấm áp và đặc biệt cho mọi dịp."},
  {id:"etoile-bracelet",name:"Vòng tay ngọc trai Étoile",category:"bracelets",pearlType:"Ngọc trai nước ngọt",price:219,material:"Bạc sterling",size:"6,5–7 mm",dimensions:"Dài 6,5 inch + dây nối 1 inch",code:"TY-B03",image:"images/etoile-bracelet.svg",description:"Chòm sao tinh tế từ những viên ngọc trai và ngôi sao đánh bóng, có thể đeo riêng hoặc kết hợp cùng trang sức thường ngày."},
  {id:"aurora-ring",name:"Nhẫn ngọc trai Aurora",category:"rings",pearlType:"Ngọc trai Akoya",price:289,material:"Vàng vermeil 18K",size:"8 mm",dimensions:"Đai nhẫn điều chỉnh được",code:"TY-R04",image:"images/aurora-ring.svg",description:"Một viên ngọc trai Akoya được nâng niu trong thiết kế bắt sáng mềm mại. Món trang sức nhỏ mang vẻ rạng ngời thanh lịch mỗi ngày."},
  {id:"celeste-set",name:"Set ngọc trai Celeste",category:"sets",pearlType:"Ngọc trai nước ngọt",price:395,oldPrice:438,material:"Vàng vermeil 14K",size:"7 mm",dimensions:"Dây chuyền 16 inch · bông tai 0,4 inch",code:"TY-S05",image:"images/celeste-set.svg",description:"Sự kết hợp hài hòa giữa bông tai Celeste và dây chuyền ngọc trai thanh mảnh, sẵn sàng làm quà tặng cho những dịp đặc biệt."},
  {id:"maris-hoops",name:"Bông tai vòng ngọc trai Maris",category:"earrings",pearlType:"Ngọc trai nước ngọt",price:159,material:"Vàng bọc",size:"6 mm",dimensions:"Đường kính 0,7 inch",code:"TY-E06",image:"images/maris-hoops.svg",description:"Vòng tai thanh mảnh, sáng bóng với điểm nhấn là những viên ngọc trai nhỏ. Một chút ánh sáng cho phong cách mỗi ngày."},
  {id:"solace-necklace",name:"Dây chuyền ngọc trai Solace",category:"necklaces",pearlType:"Ngọc trai baroque",price:249,material:"Bạc sterling",size:"9–10 mm",dimensions:"Dây chuyền dài 18 inch",code:"TY-N07",image:"images/solace-necklace.svg",description:"Viên ngọc trai baroque độc bản trên nền dây bạc tinh giản. Tự nhiên, hiện đại và mang nét riêng không thể lặp lại."},
  {id:"nacre-stack",name:"Bộ nhẫn ngọc trai Nacre",category:"rings",pearlType:"Ngọc trai Akoya",price:310,material:"Vàng nguyên khối 14K",size:"6 mm",dimensions:"Cỡ nhẫn 5–9",code:"TY-R08",image:"images/nacre-stack.svg",description:"Hai đai nhẫn thanh mảnh cùng một viên ngọc trai Akoya nhỏ. Thiết kế điêu khắc với chút bất đối xứng đầy cá tính."}
];
